server:
    port: 9020
   
app:
    smtp:
        username: smtp.pritam@gmail.com
        password: Pass@M1034079
        port: 587
        host: smtp.gmail.com
    api:
        mintopay: http://192.168.0.26:8080
   

